### ISSUE TITLE
php5-fpm logrotate error

### ISSUE THREAD

**Issue by patrickheeney** [debops/ansible-php5#5]
I received this error email today:

```
/etc/cron.daily/logrotate:
initctl: invalid command: reopen-logs
Try `initctl --help' for more information.
invoke-rc.d: initscript php5-fpm, action "reopen-logs" failed.
error: error running non-shared postrotate script for /var/log/php5-fpm.log of '/var/log/php5-fpm.log /var/log/php5-fpm/*.log '
run-parts: /etc/cron.daily/logrotate exited with return code 1
```

This looks to be the proposed fix for ubuntu 14.04: http://blog.martinshouse.com/2014/08/fixed-ubuntu-server-cron-error-message.html . For the propose fix, should we check the distro and version and adjust the template?

**Comment by drybjed** [comment]
@patrickheeney Did you get this error on Ubuntu 14.04?

**Comment by patrickheeney** [comment]
@drybjed Yes

**Comment by drybjed** [comment]
On Jessie, `php5-fpm` logrotate looks like:
```
/var/log/php5-fpm.log {
        rotate 12
        weekly
        missingok
        notifempty
        compress
        delaycompress
        postrotate
                /usr/lib/php5/php5-fpm-reopenlogs
        endscript
}
```
I guess it's time to update the one in the role. Check if you have that wrapper script on your installation.

**Comment by drybjed** [comment]
Yup, the old version is still in Wheezy, but it changed on Jessie. Which version do you have in Ubuntu?

**Comment by patrickheeney** [comment]
`/usr/lib/php5/php5-fpm-reopenlogs` exists for me when running php 5.6 from `ppa:ondrej/php5-5.6` on `ubuntu 14.04`.
