### ISSUE TITLE
max_execution_time (request_terminate_timeout) needs to be customizable

### ISSUE THREAD

**Issue by mbarcia** [debops/ansible-php5#7]
Currently, there is no way of customizing max_execution_time in php.ini (request_terminate_timeout in the pool.conf).

This value is important for users and it should be customizable.

I will be submitting a PR that adds this improvement and other minor changes to the php role.

**Comment by drybjed** [comment]
[This is now possible](https://github.com/debops/ansible-php/blob/master/defaults/main.yml#L556-L559) in the [`debops.php`](https://github.com/debops/ansible-php) role which superseded this one. I'm closing this issue.
